config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: [:show]
  resources :mutants, except: [:show]
  resources :teams, except: [:show]
  root to: 'tasks#index'
end

app/models/mutant.rb
class Mutant < ActiveRecord::Base
  belongs_to :team
  validates :name, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :team, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :team
  validates :team, presence: true
  validates :name, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :description, presence: true

  scope :desc, -> { order("created_at DESC") }
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :mutants
  has_many :tasks
  validates :name, presence: true, uniqueness: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mutants_controller.rb
class MutantsController < ApplicationController
  before_action :set_mutant, only: [:edit, :update, :destroy]
  before_action :load_teams, only: [:new, :edit, :create, :update]

  def index
    @mutants = Mutant.all
  end

  def new
    @mutant = Mutant.new
  end

  def edit
  end

  def create
    @mutant = Mutant.new(mutant_params)

    if @mutant.save
      redirect_to mutants_path, notice: 'Mutant was successfully created.'
    else
      render :new
    end
  end

  def update
    if @mutant.update(mutant_params)
      redirect_to mutants_path, notice: 'Mutant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @mutant.destroy
    redirect_to mutants_url, notice: 'Mutant was successfully destroyed.'
  end

  private
  def set_mutant
    @mutant = Mutant.includes(:team).find(params[:id])
  end

  def load_teams
    @teams = Team.all
  end

  def mutant_params
    params.require(:mutant).permit(:name, :team_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]

  def index
    @tasks = Task.desc.all
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_url, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_url, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private

  def set_task
    @task = Task.includes(:team).find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :team_id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:edit, :update, :destroy]

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def edit
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to teams_path, notice: 'Team was successfully created.'
    else
      render :new
    end
  end

  def update
    if @team.update(team_params)
      redirect_to teams_path, notice: 'Team was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @team.destroy
    redirect_to teams_url, notice: 'Team was successfully destroyed.'
  end

  private

  def set_team
    @team = Team.find(params[:id])
  end

  def team_params
    params.require(:team).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Tasks', tasks_path %></li>
<li><%= link_to 'Teams', teams_path %></li>
<li><%= link_to 'Mutants', mutants_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Freakshow" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Freakshow" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/mutants/_form.html.erb
<%= simple_form_for(@mutant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.association :team, collection: @teams, as: :select %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mutants/edit.html.erb
<h1>Editing Mutant</h1>

<%= render 'form' %>

<%= link_to 'Show', @mutant %> |
<%= link_to 'Back', mutants_path %>

app/views/mutants/index.html.erb
<h1>Listing Mutants</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Team</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @mutants.each do |mutant| %>
      <tr>
        <td><%= mutant.name %></td>
        <td><%= mutant.team.name %></td>
        <td><%= link_to 'Edit', edit_mutant_path(mutant) %></td>
        <td><%= link_to 'Destroy', mutant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mutant', new_mutant_path %>

app/views/mutants/new.html.erb
<h1>New Mutant</h1>

<%= render 'form' %>

<%= link_to 'Back', mutants_path %>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.association :team %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing Tasks</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.team.name %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>